var availableCoins = ["bitcoin","ethereum","ripple","bitcoin-cash","litecoin","cardano","stellar","neo","iota","monero","dash","nem","ethereum-classic","qtum","lisk","bitcoin-gold","nano","zcash","verge","siacoin","stratis","steem","bytecoin-bcn","waves","bitcoin-diamond","bitshares","dogecoin","decred","komodo","hshare","ark","ardor","cryptonex","pivx","digibyte","factom","monacoin","gxchain","syscoin","electroneum","zcoin","neblio","reddcoin","nxt","emercoin","byteball","particl","minexcoin","nexus","vertcoin","bitcoindark","achain","blocknet","bitcore","smartcash","gamecredits","poa-network","skycoin","nav-coin","ubiq","boscoin","pura","zencash","digitalnote","asch","bridgecoin","experience-points","salus","xtrabytes","ion","bitbay","peercoin","feathercoin","einsteinium","gulden","casinocoin","library-credit","metaverse","counterparty","viacoin","html-coin","burst","aeon","unobtanium","cloakcoin","ravencoin","groestlcoin","dimecoin","elastic","blakestar","crown","potcoin","namecoin","leocoin","eccoin","deeponion","shift","bean-cash","decent","whitecoin","steem-dollars","flash","iocoin","linkeye","blackcoin","peerplays-ppy","mooncoin","diamond","e-dinar-coin","nolimitcoin","sibcoin","vericoin","gridcoin","revolutionvr","linda","lykke","monetaryunit","primecoin","pascal-coin","zclassic","prizm","shield-xsh","omni","bitshares-music","solarcoin","electra","expanse","bitconnect","radium","universal-currency","hempcoin","zoin","mintcoin","spectrecoin","firstcoin","lomocoin","florincoin","phore","energycoin","faircoin","russian-mining-coin","tao","clams","alqo","bismuth","rubycoin","newyorkcoin","bitsend","auroracoin","colossusxt","toacoin","dubaicoin-dbix","transfercoin","posw-coin","myriad","oxycoin","boolberry","atbcoin","okcash","gobyte","musicoin","greencoin","neoscoin","the-champcoin","espers","solaris","rise","gambit","asiacoin","dynamic","pandacoin-pnd","luxcoin","sphere","novacoin","interplanetary-broadcast-coin","golos","dopecoin","sequence","syndicate","heat-ledger","stealthcoin","pinkcoin","bulwark","curecoin","internet-of-people","atmos","1337coin","pirl","biocoin","uniform-fiscal-object","geocoin","chips","denarius-dnr","artbyte","mixin","bitmark","korecoin","nubits","synergy"];
var availableTokens = ["eos","tron","tether","vechain","binance-coin","icon","omisego","digixdao","populous","ontology","rchain","maker","bytom","aeternity","augur","veritaseum","waltonchain","status","zilliqa","0x","aion","kucoin-shares","loopring","basic-attention-token","ethos","nebulas-token","qash","iostoken","golem-network-tokens","gas","dragonchain","revain","funfair","storm","kyber-network","aelf","salt","request-network","substratum","kin","nucleus-vision","chainlink","maidsafecoin","enigma-project","power-ledger","dentacoin","tenx","dent","bancor","nuls","metal","cindicator","storj","iconomi","polymath-network","enjin-coin","xpa","matrix-ai-network","genaro-network","credits","pillar","aragon","genesis-vision","decentraland","cube","civic","mithril","rlc","singularitynet","quantstamp","theta-token","time-new-bank","dynamic-trading-rights","raiden-network-token","gnosis-gno","monaco","santiment","poet","sirin-labs-token","wax","ignis","oyster","cybermiles","dew","fusion","bibox-token","gifto","arcblock","high-performance-blockchain","paypie","edgeless","telcoin","pundi-x-old","sophiatx","blockv","ethlend","envion","bluzelle","thekey","adx-net","medibloc","scryinfo","ripio-credit-network","ost","eidoo","medishares","c20","loom-network","sonm","iot-chain","amber","synereo","airswap","smartmesh","red-pulse","quantum-resistant-ledger","modum","crypterium","vibe","jibrel-network","utrust","district0x","streamr-datacoin","singulardtv","data","origintrail","spankchain","wings","ormeus-coin","appcoins","taas","naga","melon","bread","deepbrain-chain","wabi","wepower","trinity-network-credit","rock","soarcoin","tierion","etherparty","bottos","mobilego","qlink","universa","ins-ecosystem","centra","blockmason","wagerr","delphy","iht-real-estate-protocol","ink","spacechain","indahash","triggers","game","blox","bitcny","presearch","kickico","havven","mobius","tomochain","humaniq","uptoken","viberate","tokencard","unikoin-gold","cpchain","lunyr","monetha","hive-project","decision-token","nimiq","ucash","pepe-cash","odyssey","suncontract","everex","refereum","spectre-dividend","cofound-it","fortuna","internet-node-token","zeepin","safe-exchange-coin","datum","yoyow","attention-token-of-media","adtoken","blockport","medical-chain","republic-protocol","dai","bankex","stk","electrifyasia","zap","numeraire"];

var available = {};

available.Coin = (coinID) => {
    if (availableCoins.indexOf(coinID)>-1) return true;
    return false;
}

available.Token = (tokenID) => {
    if (availableTokens.indexOf(tokenID)>-1) return true;
    return false;
}

module.exports = available;